[package]
name = "crustboard"
version = "0.1.0"
edition = "2024"

[dependencies.rusqlite]
version = "0.32.0"
features = ["bundled"]

[dependencies.tokio]
version = "1.21.2"
features = ["macros", "rt-multi-thread"]

[dependencies.poise]
version = "0.6"
